### PR TITLE
Add minimal responsive behaviour

### PR DESCRIPTION
**Pull request by mcmd**
Added minimal responsive behaviour so the page works better in mobile devices.

### CODE REVIEW

**Comment by mcmd** [comment]
You can see how it looks [here](https://mcmd.github.io/mistake-o-tron/) (I've also updated the default username, but only for my gh pages deployment)

**Review by tailuge — APPROVED** [review]
This is great - did you do it to work better on phones?

**Comment by tailuge** [comment]
Thanks.

**Comment by tailuge** [comment]
Thanks

**Comment by mcmd** [comment]
Yes, I wanted to be able to use the tool in my phone comfortably when not at home. Thanks for merging 😊.

**Pull request merged**
